version: '3.8'
services:
  pocketbase:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - pb_volume:/app/pb_data
    ports:
      - "8090:8090"
  web_server:
    build:
      context: ../../web
      dockerfile: Dockerfile
      args:
        - OPENAI_KEY=${OPENAI_KEY}
        - POCKETBASE_ADMIN_USER=${POCKETBASE_ADMIN_USER}
        - POCKETBASE_ADMIN_PW=${POCKETBASE_ADMIN_PW}
        - WEB_DOMAIN=${WEB_DOMAIN}
        - PUBLIC_DEFAULT_TOOL=${PUBLIC_DEFAULT_TOOL}
    depends_on:
      - pocketbase
    restart: always
  nginx:
    image: nginx:1.25.3-alpine
    restart: always
    depends_on:
      - pocketbase
      - web_server
    environment:
      - DOMAIN=localhost
    ports:
      - "81:81"
      - "5173:81"
    volumes:
      - ../data/nginx:/etc/nginx/conf.d
    command: > 
      /bin/sh -c "sleep 10 &&
        envsubst '$$\{DOMAIN\}' < /etc/nginx/conf.d/app.conf.template.dev > /etc/nginx/conf.d/app.conf &&
        while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\""
volumes:
  pb_volume:
